### ISSUE TITLE
E-step only to 186

### ISSUE THREAD

**Issue by Mr-Rog** [Jyers/Marlin#190] opened 2021-03-06 11:02 UTC
Hello 
I have buy a BondTech extrudor, in the Manual says i must setup the e-Steps to 415 but I check in the firmware gos only to steps/mm 186
is this possible to change this, will pay for the work no problem
thx for a short feedback

**Comment by Schnabulation** [comment] 2021-03-06 13:19
The issue is already known and will be fixed in the next release.

Consider donating - helps him a lot...

**Comment by Mr-Rog** [comment] 2021-03-06 13:32
Hi Schnabulation 
thx for your answer, how i can donate?
can I ask you a question I use for my Ender 3 V2 Bltouch this version
E3V2-BLTouch-5x5-HS-V4.bin
is this OK
also I mount a BondTech extrudor, I read I neet to setup in Cura  M92 E415 is this steps/mm xxx this setting?
sorry wor asking but I dont know person they use the same Firmware
thx and cheers
Oh gerade gesehen, auch aus der Schweiz ;-)

**Comment by Schnabulation** [comment] 2021-03-06 15:12
Oh hi there, fellow Swiss. :-)
If it‘s ok, I will keep stay with English so the others can understand us. But if you want, you can send me a PM and we can talk in German.

Regarding the e-steps: Best would be to set them in the firmware. For now it is only possible to set it to 186 through the menu - but if you self-compile the firmware you can go higher. I don‘t know the command to set it through Cura though.

And btw: on the main repo page of this firmware on the top right is a „Sponsor“ button. ;-)

**Comment by tititopher68** [comment] 2021-03-06 20:29
Just to modify line 2028 in \src\lcd\extui\lib\creality_dwin\creality_dwin.cpp :  

Modify_Value(planner.settings.axis_steps_per_mm[E_AXIS], 0, **default_steps[E_AXIS]*2**, 10);

by : 

Modify_Value(planner.settings.axis_steps_per_mm[E_AXIS], 0, **1000**, 10);

;-) !

**Comment by Mr-Rog** [comment] 2021-03-06 20:55
thy I will check, but when I donwload the code and check it for me line1895
also change the line nothing more, try to Visual Studio Code Try to Build, but gets a lot of error ;-) ok its my first time

...............
Marlin\src\inc/SanityCheck.h:1425:6: error: #error "Z_MIN_PROBE_REPEATABILITY_TEST requires a probe: FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, BLTOUCH, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo."
     #error "Z_MIN_PROBE_REPEATABILITY_TEST requires a probe: FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, BLTOUCH, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo."
      ^~~~~
In file included from Marlin\src\core\../inc/MarlinConfig.h:49:0,
                 from Marlin\src\core\serial.h:24,
                 from Marlin\src\core\serial.cpp:23:
Marlin\src\core\../inc/SanityCheck.h:1425:6: error: #error "Z_MIN_PROBE_REPEATABILITY_TEST requires a probe: FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, BLTOUCH, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo."
     #error "Z_MIN_PROBE_REPEATABILITY_TEST requires a probe: FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, BLTOUCH, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo."
...............................

#if ENABLED(Z_MIN_PROBE_REPEATABILITY_TEST)
    #error "Z_MIN_PROBE_REPEATABILITY_TEST requires a probe: FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, BLTOUCH, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo."
  #endif
maybe you have a hint for me
cheers

**Comment by Jyers** [comment] 2021-03-07 03:28
Issue resolved with #187, will be available in the next release. If you want any more help compiling, I recommend opening a discussion thread :)

**Closed as completed by Jyers** 2021-03-07 03:28 UTC
