### ISSUE TITLE
E3V2-UBL-BLTouch-10x10-HS-v4.2.2-v2.0.0.bin hangs after load filament

### ISSUE THREAD

**Issue by jamiecarl** [Jyers/Marlin#1538] opened 2021-10-26 01:26 UTC
### Description

After going through the load filament process, filament is extruded from the hotend but then the system hangs on the "Loading filament" screen and never returns.

I used to have a similar problem prior to the 2.0.0 relelase (#1186) where the system would crash if you leave the filament load screen too quickly.  Is this the fix for it?  lol

### Steps to Reproduce

1. Pre-heat the hotend
2. Run the "Load Filament" process
3. Watch the filament extrude

**Expected behavior:**

Screen should show the "extrude more filament?" question screen which allows more filament to be extruded or to end the process.

**Actual behavior:** 

Screen sits on "loading filament" screen and never returns.  Can't do anything from here other than switch the machine off and on again.

#### Additional Information

This should be easy to reproduce as it happens consistently for me when loading filament from the LCD.

**Comment by tome9111991** [comment] 2021-10-26 09:59
I can confirm

**Comment by DrewLX** [comment] 2021-10-26 21:11
Same for me too, for M600 filament changes too. I've also tried the non-HS variant which performs the same. I haven't tried other variants yet but I would imagine they are the same.

**Comment by Turtleturd101** [comment] 2021-10-26 23:11
Samesies. Last night I let it sit at the "wait for prompt" screen overnight.

**Comment by kooopa** [comment] 2021-10-28 13:10
Same Here

**Comment by theoden11** [comment] 2021-10-30 10:43
Hello. Same problem with E3V2-Default-v4.2.2-v2.0.0.bin and with my own proper compiled firmware from your source. Everything works except pause/resume. When pausing whatever the reason, it won't resume and Ender is stuck.

**Comment by Jyers** [comment] 2021-11-03 02:46
Should be fixed with the latest commit. If you compile your own version give it a try and report back, otherwise wait for the next release and try it

**Comment by theoden11** [comment] 2021-11-03 18:44
Thanks. Meanwhile I compiled a 1.3.5b firmware with success and there's no more problem with filament change, pause or whatever. For me, that's the solution ! (endly I've got a Z-350mm firmware that works with other options !)

**Comment by Jyers** [comment] 2021-11-05 21:23
Release is out, give it a try and report back

**Comment by jamiecarl** [comment] 2021-11-05 23:36
> Release is out, give it a try and report back

Thanks @Jyers .  I can confirm this is now fixed.  

Once the purging is done, the screen now asks to purge more or cancel.  Doing either works as expected and it returns to the previous screen when completed. 

I will go test #1551 for those guys as well as I have no print jobs for today.  I'll also test that runout sensor issue and see if it's OK now, or submit an issue if it's not.

Thanks again for all your work on this project.  Much appreciated.

**Comment by Jyers** [comment] 2021-11-06 00:09
Glad all is well, and thanks so much for the testing 😁

**Closed as completed** 2021-11-06 00:09 UTC
