### ISSUE TITLE
Display freezing after Filament Runout, in last Updated 

### ISSUE THREAD

**Issue by mosheas** [Jyers/Marlin#175] opened 2021-03-04 10:13 UTC
After last Updated, during sensor filament runout  prosses the display get freeze, please see attached video show the phenomenon , thank you. 

https://youtu.be/UMNVy43oLgw

**Comment by Schnabulation** [comment] 2021-03-04 10:15
Duplicate of this: https://github.com/Jyers/Marlin/issues/174

**Comment by mosheas** [comment] 2021-03-04 10:18
this is a new problem happen on last Updated before few days

**Comment by mosheas** [comment] 2021-03-04 10:21
No, this is a new issue that appeared a few days ago in the last update, before that it worked fine.

**Comment by Schnabulation** [comment] 2021-03-04 10:23
If you would check my comment, you would see, that I created that issue **this morning.** So yes, this a new issue that arrived with the latest firmware.

**Comment by mosheas** [comment] 2021-03-04 10:34
OK, thanks. I will close it

**Closed as completed** 2021-03-04 10:34 UTC

**Comment by mosheas** [comment] 2021-03-04 10:36
Double issue

**Comment by Schnabulation** [comment] 2021-03-04 10:39
> OK, thanks. I will close it

Thanks. You can comment on my issue with your YouTube video - that helps a lot.
