### ISSUE TITLE
[BUG] M73 showes wierd percentages in new branch

### ISSUE THREAD

**Issue by Schnabulation** [Jyers/Marlin#44] opened 2021-02-16 09:00 UTC
### Bug Description

In the new Ender_3_V2_Extensible_UI branch the M73 command gives some wierd percentages on the screen when printing from OctoPrint:

![IMG_2987](https://user-images.githubusercontent.com/1053834/108040166-4487d280-703d-11eb-8173-ee9763cfd25e.JPG)

### Configuration Files

Find my configuration files in my fork: https://github.com/Schnabulation/Marlin/tree/Ender_3_V2_Extensible_UI/Marlin

The most importand configs would be these:

`#define LCD_SET_PROGRESS_MANUALLY`
`#define USE_M73_REMAINING_TIME`

I am using [M73 Progress Plugin](https://plugins.octoprint.org/plugins/m73progress/) and [DisplayLayerProgress Plugin](https://plugins.octoprint.org/plugins/DisplayLayerProgress/) in OctoPrint.

### Steps to Reproduce

Just print normally through OctoPrint. You could also check by manually sending a "M73 P25" through the terminal.

**Comment by Jyers** [comment] 2021-02-16 16:34
I can confirm this issue. Based on my testing it seems to be multiplying the percent give by 100 and the strange number you see is an overflow error.

**Comment by clintiepoo** [comment] 2021-02-17 03:04
Same issue here - if you need another test case.

**Comment by Jyers** [comment] 2021-02-17 08:45
This is fixed in the build # 1.1

**Closed as completed by Jyers** 2021-02-17 08:45 UTC
