### ISSUE TITLE
v1.3.2 - no control screen during printing

### ISSUE THREAD

**Issue by czaras** [Jyers/Marlin#860] opened 2021-05-18 18:33 UTC
I've installed to my Ender 3v2 this firmware: E3V2-ManualMesh-3x3-v4.2.2.bin

When I start printing the printer screen shows a regular print screen with Tune button etc. but after a few minutes the display goes back to home screen and there's no option to display a control screen again althought the printing is still in progress, you're not able to pause or tune the current ongoing job.

I did reinstall this firmware twice but the story is still the same.

**Comment by tititopher68** [comment] 2021-05-18 22:10
@czaras 
Have you tried compiling your own firmware with the latest build?

**Comment by SikVac** [comment] 2021-05-19 06:23
I have the same problem. When printing starts, the screen switches to the home screen.
I solve this by switching to the Tune option immediately after starting printing. During printing, you can then select the Back option again, which puts me on the print screen. with TUNE.

**Comment by czaras** [comment] 2021-05-19 07:06
ok, good to know the temporary solution ;) but it’s an obvious bug, right? ;)

         
Powered by Mailbutler <https://www.mailbutler.io/?utm_source=watermark&utm_medium=email&utm_campaign=watermark-essential-email>, the email extension that does it all

**Comment by tititopher68-dev** [comment] 2021-05-19 07:41
@SikVac @czaras Sorry but, no issue with the last build on line. You have to compile your own firmware...

**Comment by Cal-LF** [comment] 2021-05-19 11:29
The next release will fix this issue. I had the same thing happen and compiling the 3X3 man mesh template fixes it.

**Comment by Qubi-B** [comment] 2021-05-21 11:42
does it do the same with 5x5 manualmesh or without manual mesh at all?

**Comment by SikVac** [comment] 2021-05-22 06:49
To Qubi-B
With version "E3V2-UBL-BLTouch-15x15-HS-v4.2.2.bin"

**Comment by Jyers** [comment] 2021-05-22 16:40
As a temporary fix, I believe this is caused by having M501 in your start gcode. Removing this should fix the issue. As @Cal-LF said though, this has been fixed and will be in the next release

**Closed as completed by Jyers** 2021-05-22 16:40 UTC
