### ISSUE TITLE
2.0.0 LCD coordinates are incorrect

### ISSUE THREAD

**Issue by jamiecarl** [Jyers/Marlin#1546] opened 2021-10-26 23:04 UTC
### Description

Looks like the LCD coordinates are off by a factor of 10 on the X and Y axes, and 100 on the Z axes on the new 2.0.0 firmware.  I'm runing E3V2-UBL-BLTouch-10x10-HS-v4.2.2-v2.0.0.bin but I'm sure it's consistent across builds.  Can anyone confirm?

Screen just after doing a "Home All".  The first thing I noticed was that the Z position was my Z-Offset multiplied by 100.
![IMG_2021-10-27-09-52-21-926](https://user-images.githubusercontent.com/558592/138973089-1ea27aff-ee80-4d94-91ff-250f5c695ad5.jpg)

Screen when manually moving the carriage to 1-1-1 position.  As you can see, the LCD coordinates are x10 on the X and Y, and x100 on the Z.
![IMG_2021-10-27-09-53-39-686](https://user-images.githubusercontent.com/558592/138973143-64e7174f-ab14-4948-ac61-129ebf3b91cd.jpg)

### Steps to Reproduce

1. Turn the machine on
2. Home All
3. Look at LCD screen

**Expected behavior:** 

LCD coordinates should show correct XYZ coordinates.

**Actual behavior:**

LCD shows coordinates multiplied by 10 on the X and Y axes, and multipled by 100 on the Z axes.

#### Additional Information

Home the machine and move the carriage to 0-0-0 and the display will show 0-0-0, so it's definately a multiplier issue.

**Comment by Jyers** [comment] 2021-10-27 04:06
Fixed with #1521 will be in the next release

**Closed as completed by Jyers** 2021-10-27 04:06 UTC

**Comment by jamiecarl** [comment] 2021-10-27 04:20
Thanks @Jyers !

**Comment by jamiecarl** [comment] 2021-10-31 22:30
Hey @Jyers .  Any idea if this would actually cause a problem with the OctoPi Smart Filament Sensor plugin?  Something like, this issue is causing the distance detection to not work because the E axis is off?  I don't know enough about how the two work together to say myself.  But unfortunately I've had to roll back to 1.3.5 because my prints kept pausing saying the filament had run out.  I thought it was OctoPi, but the rollback from 2.0.0 to 1.3.5 fixed the issue.  If it's not related to this, I will test on the next release and submit a new issue at that time.  Cheers.

**Comment by Jyers** [comment] 2021-11-03 00:46
It shouldn't be related... I'll let you know if I come across anything that may affect that.

**Comment by jamiecarl** [comment] 2021-11-05 23:45
> It shouldn't be related... I'll let you know if I come across anything that may affect that.

Just noting that my problem with the Smart Filament Sensor plugin for OctoPrint is no longer an issue on the 2.0.1 firmware.  I can't shake the feeling it is related to this.  But clearly something you fixed in 2.0.1 has ended up fixing this problem as well.  Thanks @Jyers .

**Comment by Jyers** [comment] 2021-11-06 00:12
Might have been fixed by switching back to the old stm32 environment. That was the cause of many many bugs.
