### ISSUE TITLE
M48 Issue 

### ISSUE THREAD

**Issue by eblieb** [Jyers/Marlin#1321] opened 2021-08-18 18:49 UTC
Running v1.3.5.B 
3V2-UBL-BLTouch-10x10-HS-v4.2.2-v1.3.5.b.bin and can  not run an M48. 

Symptoms are 
Run G28 - Homes fine
Run M48 

2021-08-18 14:20:22,888 - Send: N3 M48*28
2021-08-18 14:20:22,902 - Recv: M48 Z-Probe Repeatability Test
2021-08-18 14:20:23,773 - Recv:  T:25.77 /0.00 B:25.51 /0.00 @:0 B@:0
2021-08-18 14:20:24,895 - Recv: echo:busy: processing
2021-08-18 14:20:25,773 - Recv:  T:26.24 /0.00 B:25.36 /0.00 @:0 B@:0
2021-08-18 14:20:26,894 - Recv: echo:busy: processing
2021-08-18 14:20:27,773 - Recv:  T:26.14 /0.00 B:25.55 /0.00 @:0 B@:0
2021-08-18 14:20:28,894 - Recv: echo:busy: processing
2021-08-18 14:20:29,773 - Recv:  T:26.16 /0.00 B:25.51 /0.00 @:0 B@:0
2021-08-18 14:20:30,894 - Recv: echo:busy: processing
2021-08-18 14:20:33,901 - Communication timeout while idle, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regul$
2021-08-18 14:20:35,852 - Recv: start

Then nothing.

**Comment by tititopher68-dev** [comment] 2021-08-18 19:25
@eblieb 
According to your comment, it's  certainly just a hardware issue

**Comment by eblieb** [comment] 2021-08-18 19:51
Nope reverted back to E3V2-UBL-BLTouch-10x10-HS-v4.2.2-v1.3.5.bin and I was able to run M48 without an issue. So it is something in the Marlin source that 1.3.5.b was updated to. I tried to submit the bug report in the Marlin git but they said they wont support a bug if it is in a fork, eventho it is in their source.

**Comment by tititopher68-dev** [comment] 2021-08-18 20:32
@eblieb 
I investigated.  No change in sources between versions 1.3.5 and 1.3.5.b for M48.  Have you tried from the interface?
 Your Terminal return indicates a communication error (Time out with Printer communication).

**Comment by Tuncay-Ayhan** [comment] 2021-08-18 20:35
I can confirm this problem also. I have communicated with @Jyers about this
via Discord. It’s an issue I also have since 1.3.5 . 1.3.4 doesn’t have
this issue.

It’s very random and I’ve tried different approaches. From GCode on SD to
Octoprint etc.

Nothing seems to make sense. When reverting back to 1.3.4 the issues is non
existent.


Op wo 18 aug. 2021 om 22:32 schreef tititopher68-dev <
***@***.***>

**Comment by Tuncay-Ayhan** [comment] 2021-08-18 20:46
> @eblieb
> I investigated. No change in sources between versions 1.3.5 and 1.3.5.b for M48. Have you tried from the interface?
> Your Terminal return indicates a communication error (Time out with Printer communication).

I can confirm this problem also. I have communicated with @Jyers about this
via Discord. It’s an issue I also have since 1.3.5 . 1.3.4 doesn’t have
this issue.

It’s very random and I’ve tried different approaches. From GCode on SD to
Octoprint etc.

Nothing seems to make sense. When reverting back to 1.3.4 the issues is non
existent.

<p>

<p>

### When using the <s>manual leveling</s> M48 <s>with probe</s> function on the printer itself
<details>
  <summary>Click to expand!</summary>
  
  ```
  Recv: Error:Probing Failed
WARNING! Received an error from the printer's firmware, ignoring that as configured but you might want to investigate what happened here! Error: Probing Failed
Recv: //action:notification Probing Failed
Recv: Error:Probing Failed
WARNING! Received an error from the printer's firmware, ignoring that as configured but you might want to investigate what happened here! Error: Probing Failed
Recv: //action:notification Probing Failed
Recv: Error:Probing Failed
WARNING! Received an error from the printer's firmware, ignoring that as configured but you might want to investigate what happened here! Error: Probing Failed
Recv: //action:notification Probing Failed
Recv: Error:Probing Failed
WARNING! Received an error from the printer's firmware, ignoring that as configured but you might want to investigate what happened here! Error: Probing Failed
Recv: //action:notification Probing Failed
Recv: Error:Probing Failed
WARNING! Received an error from the printer's firmware, ignoring that as configured but you might want to investigate what happened here! Error: Probing Failed
  ```
</details>

<p>

<p>

### Video 1.3.5 M48 - Dying screen and no M48 execution
[Video](https://user-images.githubusercontent.com/28215053/129969610-cc8fcfd9-9423-4844-a61d-193474652228.mov)


EDIT:

Jus FYI, I've also increased all the communication time outs within Octoprint. It doesn't seem to make an difference. At the end, it will crash again. The only difference is, is that Octoprint doesn't need to reconnect to the printer. Instead it stays connected but doesn't execute the command. 

I've tried Exectuting from SD Card as a GCODE file > Not working
Execute as an Custom Control with a plugin within Octoprint > Not working
Trying out the M48 that is build in the screen > Not working
Octoprint terminal > Not working

Also, like recommended after flashing.
```Resetting the printer```
```Saving```
```Restoring```
```Saving again``` 
doesn't make any difference.

**Comment by tititopher68-dev** [comment] 2021-08-18 21:16
@Tuncay-Ayhan 
I confirm that there are indeed a lot of problems with the marlin sources for 3 weeks (homing, bed leveling, autotilit, M32, M48 now ...)

**Comment by Tuncay-Ayhan** [comment] 2021-08-18 21:27
> @Tuncay-Ayhan
> I confirm that there are indeed a lot of problems with the marlin sources for 3 weeks (homing, bed leveling, autotilit, M32, M48 now ...)

I couldn't find anything obvious myself in upstream, so we'll have to wait and be patient till the moment someone finds the cause of it. Nothing to do about it as of now.  :-D

**Comment by tititopher68-dev** [comment] 2021-08-19 08:29
@Tuncay-Ayhan @Jyers @eblieb 
It seems to come from the HAL STM32 libraries ... there are 2 patches released on August 10th ...
 So either @Jyers merges again with the latest bugfixes, or we integrate the modifications for 35 files:
 Define HAL_STM32 for HAL / STM32 (MarlinFirmware # 22537)
 Update HAL / STM32 wrappers
 Followup to MarlinFirmware # 22537

**Comment by Tuncay-Ayhan** [comment] 2021-08-19 10:49
> @Tuncay-Ayhan @Jyers @eblieb 
> 
> It seems to come from the HAL STM32 libraries ... there are 2 patches released on August 10th ...
> 
>  So either @Jyers merges again with the latest bugfixes, or we integrate the modifications for 35 files:
> 
>  Define HAL_STM32 for HAL / STM32 (MarlinFirmware # 22537)
> 
>  Update HAL / STM32 wrappers
> 
>  Followup to MarlinFirmware # 22537

It's good to hear you've found the possible fixes. Now we'll have to wait for Jyers.

**Comment by tititopher68-dev** [comment] 2021-08-19 12:12
@Tuncay-Ayhan 
Tonight, I will compile a version with these fixes and we'll see ...

**Comment by eblieb** [comment] 2021-08-20 18:45
Just reverted back to 1.3.4 and all of my BLTouch issues are gone. I was constantly having issues on 1.3.5 and 1.3.5.b

**Comment by tititopher68-dev** [comment] 2021-08-20 21:37
@Tuncay-Ayhan @eblieb @Jyers 

OK it's a HAL STM32 issue. 
I integrated all the modifications for STM32 and No screen glitch, M48 OK, ABL G29 OK

I worked on a BTT skr E3 mini V2 (compilation issue) with this firmware 1.3.5b and  no issues.

**Comment by eblieb** [comment] 2021-08-20 21:41
Nice... hopefully it gets merged into Jyers firmware soon. I just ordered a CRTouch on Amazon to replace my BLTouch... The cable on the BLTouch is going bad because it doesnt use the proper connector

**Comment by tititopher68-dev** [comment] 2021-08-20 21:43
@Jyers 
I think it would be necessary to merge the latest Marlin bugfixes again to fix all this issues...

**Comment by Jyers** [comment] 2021-08-21 00:46
@tititopher68-dev Done 😄 

Sorry I've been a bit absent lately, I've had some quite tasking responsibilities this week along with a rapidly approaching move

**Comment by tititopher68-dev** [comment] 2021-08-21 08:11
@Jyers
 No problem !  Sometimes we all have other obligations ...
 Have you noticed that by modifying 4 or 5 files in the sources, it makes the firmware also compatible with BTT Skr 1.4 and E3 mini motherboards?
 In any case, good move ahead ...

 @ Tuncay-Ayhan @eblieb
 The merge has just been done, all that remains is to compile and verify that everything is functional.

**Comment by Tuncay-Ayhan** [comment] 2021-08-21 08:17
> @Jyers
> 
> No problem !  Sometimes we all have other obligations ...
> 
> Have you noticed that by modifying 4 or 5 files in the sources, it makes the firmware also compatible with BTT Skr 1.4 and E3 mini motherboards?
> 
> In any case, good move ahead ...
> 
> 
> 
> @Tuncay-Ayhan @eblieb
> 
> The merge has just been done, all that remains is to compile and verify that everything is functional.


Thanks for the headsup!

**Comment by eblieb** [comment] 2021-08-24 17:35
Any update on when the new firmware is going to be released with the bugfixes?

**Comment by eblieb** [comment] 2021-08-29 20:43
@Jyers @tititopher68-dev any update on when a new compile may be released?

**Comment by Jyers** [comment] 2021-08-30 14:46
@eblieb Sorry for the delay. I will hopefully have a new release soon. I have another feature or two to add before I do though. I've just finished moving so I should have a bit more time now to get things sorted.

**Comment by Jyers** [comment] 2021-10-24 05:32
^^^
Haha, that's a little dated huh. This is most likely fixed in the latest source since it's very up to date

**Closed as completed by Jyers** 2021-10-24 05:32 UTC
